server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mugCup
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        hibernate:
          "[format_sql]": true
          "[user_sql_comments]": true
          "[highlight_sql]": true
          "[hbm2ddl.auto]": update
  security:
    user:
      name: user
      password: 0818
